### PR TITLE
Upgrade to NAN 2.1.0 for Node 4 support

### LINKED ISSUE #11: Update to NAN 2.0
This is for Node 4+ compatibility.

### PR DESCRIPTION
**Pull request by ide**
Fixes #11

### CODE REVIEW

**Comment by ide** [comment]
PR #10 is more comprehensive and should supersede this PR, but this one may be easier to review and merge. It's causing a warning/error for people using packages that depend on crypt3.

**Comment by rolandpoulter** [comment]
:+1: This is much simpler than my approach. I didn't know anything about native extensions for node before this.

**Comment by ide** [comment]
@jheusala @rlidwka could you review this when you have a chance? Hopefully it's not too complicated, and the tests pass =)

**Comment by ide** [comment]
Updated to compile without warnings on NAN 2.1.0.

**Comment by ide** [comment]
ping

**Comment by jheusala** [comment]
Sorry, I have been busy with other work.

**Pull request merged**
